// Portfolio content, ported from the Claude Design canvas artifact.
const PROJECTS = [
  {
    id: 'jpmc',
    tag: 'Enterprise Tool',
    title: 'JPMC Corporate Challenge: Report Hub',
    blurb: 'Redesigning how stakeholders track, and share event reports.',
    role: 'Product Management',
    timeline: '10 weeks',
    tools: 'Jira, Confluence',
    overview: "Reporting is critical to running JPMC's global Corporate Challenge events. It's how Admins and Local Race Organizers manage thousands of company teams and participant logistics across 16 cities. The existing reports ran on AWS QuickSight, but with CCB support for that platform ending, staying on it created a security and compliance risk. I led product management for the migration to a custom-built reporting solution.",
    sections: [
      { heading: 'The Problem', body: "QuickSight support was being sunset, and alternatives like Tableau ran into external-access constraints for our user base. We needed a path that kept reporting supported, secure, and accessible to business users, without losing what Admins and Local Race Organizers relied on day to day." },
      { heading: 'The Approach', body: "I scoped the work around getting our core business users (OBE Administrators and Local Race Organizers, or LROs) access to the reports and data they needed for day-to-day operations, so nothing broke on cutover." },
      { heading: 'Delivery & Readiness', body: "A focused team of 3 technologists worked through the business requirements and delivered a custom replacement for the existing reporting suite in 5 sprints, with full delivery automation so future changes could ship without any external dependency. Product, Tech, and DCE completed validations to support a smooth launch, with close monitoring as usage ramped up. We also leaned on AI tooling (Copilot) for UI scaffolding, test/load testing, and synthetic data generation, for an estimated ~50% improvement in delivery productivity." },
      { heading: 'The Outcome', body: "Report Hub is now live for OBE Administrators and Local Race Organizers across all 16 cities, delivering real-time data through a supported, secure, custom-built home for reporting fully off QuickSight, saving an estimated $25K a year." },
    ],
    reflection: "This was my first time owning a migration end-to-end rather than a single feature. Scoping the work around what business users actually needed forced me to get comfortable saying 'not yet' to nice-to-haves so the essentials shipped on time, a tradeoff I now default to on every roadmap.",
  },
  {
    id: 'closet',
    tag: 'Mobile App',
    title: 'ClosetMind: Mindful Wardrobe App',
    blurb: 'Helping people build outfits from clothes they already own.',
    role: 'UX Designer & Engineer',
    timeline: '1 semester',
    tools: 'Claude Design, Claude Code',
    liveUrl: 'https://claude.ai/artifact/Q5mkKZr3WkjsEEAzQtuwMD',
    liveLabel: 'View Interactive Prototype',
    overview: 'ClosetMind is a mobile app that helps people rediscover and wear the clothes they already own. Tagline: your wardrobe, archived. Designed for my Principles of Digital Design course, this was the first project where I owned the full process myself: research, definition, design, and testing.',
    reflection: "This was my first project built entirely from my own research instead of a client brief, which meant I couldn't lean on anyone else's assumptions about the user. It pushed me to trust, and then test, my own instincts.",
    blocks: [
      { type: 'story', kicker: 'The Problem', body: "Most people wear 20% of their wardrobe 80% of the time. The rest gets forgotten behind the clothes that happen to be at the front. ClosetMind gives people a way to catalog what they own, resurface pieces they've stopped thinking about, and make outfit decisions with confidence, without buying anything new." },
      { type: 'quote', kicker: 'Research', quote: "The recurring theme wasn't a lack of clothes, it was a lack of visibility into what they already had.", points: [
        'Interviewed 4 friends and target users about how they currently plan outfits.',
        "Every one of them described the same loop: stand in front of the closet, can't decide, default to buying something new.",
        'That loop reframed the problem: how might we help someone see their wardrobe as a set of possible outfits, not a pile of individual items?',
      ]},
      { type: 'story', kicker: "Who It's For", body: "The target user is someone with a full wardrobe who still feels like they have nothing to wear." },
      { type: 'divider', kicker: 'Part One', title: 'Design System' },
      { type: 'columns', heading: 'Building the System', items: [
        { title: 'Color', body: 'Near-black and warm off-white, high contrast, editorial rather than app-y.' },
        { title: 'Type', body: 'A serif for screen titles, paired with a small-caps sans for labels.' },
        { title: 'Components', body: 'Filter pills, favoritable cards, a five-tab nav, and consistent black buttons throughout.' },
      ]},
      { type: 'divider', kicker: 'Part Two', title: 'Features' },
      { type: 'features', heading: 'What It Does', items: [
        { title: "Today's Suggestion", body: "A daily outfit recommendation pulled from the user's wardrobe, with a full detail view." },
        { title: 'Wardrobe Catalog', body: 'Grid view with filters, individual item detail, and the ability to edit or delete pieces.' },
        { title: 'Saved Outfits', body: 'Organized into folders, with an outfit grid and a detail view that lists every piece.' },
        { title: 'Build Outfit', body: 'Manually assemble an outfit from wardrobe pieces using a live selection flow.' },
        { title: 'Outfit Diary (Inspo)', body: 'Two tabs: saved looks from external inspiration, and created looks the user has logged.' },
        { title: "Log Today's Outfit", body: 'Quick capture of what you actually wore, feeding the diary.' },
        { title: 'Mira', body: 'An AI style assistant available as a chat screen for style questions and recommendations.' },
        { title: 'Auth Flows', body: 'Sign in, create account, and a three-step forgot password flow.' },
      ]},
      { type: 'divider', kicker: 'Part Three', title: 'Design Approach' },
      { type: 'story', heading: 'An editorial-first system', body: 'ClosetMind is designed editorial-first, with an aesthetic that feels more like a fashion archive than a utility app. The process started with competitive analysis and "how might we" framing, then moved to building a design system before touching any screens. Each screen was designed with options at key decision points, validated through informal user testing, and iterated from there.' },
      { type: 'story', heading: 'A deliberate restraint', body: 'The profile screen is deliberately minimal. No stats, no gamification. The focus stays on the clothes.' },
      { type: 'divider', kicker: 'Part Four', title: 'Working With Claude' },
      { type: 'workingWithAI', heading: 'What Claude Was Good For', helped: [
        'Scaffolding screens and component states quickly in Claude Design, so more time went into the flows and copy than into rebuilding basic UI from scratch.',
      ], fellShort: [
        "It couldn't tell me whether a pattern would actually make sense to someone who'd never used the app before. That only surfaced once real people tried it, which is exactly what usability testing caught." ,
      ]},
      { type: 'divider', kicker: 'Part Five', title: 'Usability Testing' },
      { type: 'story', heading: 'What I tested', body: "I walked four people through the ClosetMind prototype (design-only, no backend): a product manager, a software engineer, my target user, and a design mentor. Each ran the core flows unmoderated, at their own pace, adding a piece, matching an inspo photo, generating an outfit, and saving a look." },
      { type: 'features', heading: 'What worked', items: [
        { title: 'Instant clarity', body: 'Every tester understood the concept from the first screen. No explanation needed.' },
        { title: "Today's Suggestion wins", body: 'Two testers tapped it first when looking for an outfit, confirming it as the strongest entry point.' },
        { title: 'Alternatives read clearly', body: 'The alternatives-and-checkmarks pattern mapped instantly to "what I own vs. what I’d need."' },
        { title: 'Daily-use potential', body: "One tester said they'd use it daily, especially while traveling." },
      ]},
      { type: 'columns', heading: "What I'd change next", items: [
        { title: 'No detail view', body: "Today's Suggestion doesn't open one yet. Both non-designer testers expected it to." },
        { title: 'No onboarding', body: 'Rediscover needs a tooltip or empty state before a user has wardrobe history.' },
        { title: 'Stay free', body: "One tester said cost would be a dealbreaker, a signal to design this free, not to add a paywall later." },
      ]},
      { type: 'divider', kicker: 'Part Six', title: 'The Final Solution' },
      { type: 'imageNote', heading: 'Key Screens', note: 'Home, Wardrobe, Item Detail, Inspo, Mira, and Profile, the editorial-first system carried across every screen.', images: [
        { src: 'assets/closetmind/home.png', alt: 'ClosetMind Home screen', caption: 'Home' },
        { src: 'assets/closetmind/wardrobe.png', alt: 'ClosetMind Wardrobe catalog grid', caption: 'Wardrobe' },
        { src: 'assets/closetmind/item-detail.png', alt: 'ClosetMind item detail screen', caption: 'Item Detail' },
        { src: 'assets/closetmind/inspo-grid.png', alt: 'ClosetMind Inspo grid', caption: 'Inspo' },
        { src: 'assets/closetmind/inspo-detail.png', alt: 'ClosetMind Inspo detail with matched pieces from the wardrobe', caption: 'Inspo Detail: Matched Pieces' },
        { src: 'assets/closetmind/mira.png', alt: 'ClosetMind Mira AI style assistant chat', caption: 'Mira' },
        { src: 'assets/closetmind/profile.png', alt: 'ClosetMind Profile screen', caption: 'Profile' },
      ]},
      { type: 'imageNote', heading: 'Flow Walkthrough', note: 'Adding a piece to the wardrobe: tap the + on Home, choose how to add it (photo, barcode scan, or a pasted link), then land on Item Detail to confirm name, brand, category, size, and color.', images: [
        { src: 'assets/closetmind/home.png', alt: 'Home screen with add button', caption: '1. Tap + on Home' },
        { src: 'assets/closetmind/add-item.png', alt: 'Add to your wardrobe modal', caption: '2. Choose how to add it' },
        { src: 'assets/closetmind/item-detail.png', alt: 'Item detail confirmation screen', caption: '3. Confirm the details' },
      ]},
      { type: 'story', kicker: 'Outcome & Impact', body: "ClosetMind is currently a design-only prototype, no backend or database, built and tested in Claude Design and Claude Code. Across four usability sessions the core concept validated cleanly: every tester understood the value within seconds, and the target user confirmed it solves a problem she actually has. The clearest open threads are a detail view for Today's Suggestion, onboarding for first-time users, and deeper wardrobe organization (categories, filters, style tags) that came up as the most-requested next step." },
      { type: 'reflectionBlock', quote: "Trust it, then test it: that's the only instinct worth keeping.", keepGoing: "Add a detail view for Today's Suggestion, onboarding for first-time users, and richer wardrobe organization (categories, filters, style tags).", differently: "I'd capture process artifacts, sketches, style references, iteration rounds, as I went instead of reconstructing them afterward. A portfolio review made it clear how much stronger the story reads when that thinking is documented in the moment, not after the fact." },
    ],
  },
  {
    id: 'cafeminty',
    tag: 'Brand & Web',
    title: 'Café Minty',
    blurb: 'A personal brand hub for the matcha and desserts I make at home.',
    role: 'Solo, Brand & UX/UI Designer',
    timeline: 'Weeks 12–15, 1 semester',
    tools: 'Claude Design, Claude Code',
    liveUrl: 'https://cafe-minty.netlify.app/',
    overview: "Café Minty is a unified brand hub for a home café idea I've had for a while but never built: a place to share matcha recipes, and eventually give people a real way to try what I make, through an order drop or pop-up. It launches matcha-first but is designed as a system that can expand into coffee, desserts, and whatever comes next, without needing a redesign.",
    reflection: "Building something I'd only ever thought about, rather than a class-assigned brief, forced me to define my own scope and know when to stop polishing and ship. Class crit pushing me to be bolder, and my own instinct to cut what wasn't real yet, were both lessons in trusting a point of view.",
    blocks: [
      { type: 'story', kicker: 'Product Story', body: "I love making matcha at home, and I've always loved hosting and feeding people, but this idea has only ever lived in my head. This project was my chance to actually build it for the first time: to figure out what it looks like, how it should feel, and whether it's something I'd genuinely want to keep going after the semester ends." },
      { type: 'story', kicker: "Who It's For", body: "Right now, friends and family who see something I post on my personal Instagram and DM me asking how to make it. But it's built for anyone who finds my content, and eventually, local customers who want to order or catch a pop-up." },
      { type: 'story', kicker: 'The Value', body: "Once Café Minty exists, that same audience gets a place to actually find and return to recipes, instead of a one-off DM reply, and longer-term, a real way to order or catch a pop-up." },
      { type: 'story', kicker: 'My Role', body: 'Solo, brand and UX/UI design, weeks 12–15 of the semester, built in Claude Design and Claude Code, with original photography.' },
      { type: 'quote', quote: "I love making culturally-rooted drinks and desserts, but I have no diary-like place to even remember my own recipes, let alone somewhere for others to find them or know about a future order drop or pop-up.", points: [
        "Instagram can't hold recipes people return to.",
        "No way for anyone to actually order or find out about a pop-up.",
        "The idea only ever lived in my head, never had a real shape.",
      ]},
      { type: 'audience', heading: 'The Audience', cards: [
        { title: 'Friends & Family', body: "The first audience: people already DMing me for recipes off my personal Instagram." },
        { title: 'Content Followers', body: "Anyone who finds Café Minty through content I share, even without a prior connection to me." },
        { title: 'Local Customers', body: "Longer-term: people discovering it through a real pop-up or order drop." },
      ]},
      { type: 'divider', num: '01', kicker: 'Part One', title: 'Thinking & Process' },
      { type: 'story', heading: 'Three early directions', body: 'Before locking any system, I explored three overall moods: Matcha garden (soft sage and cream, editorial serif, safe and cohesive, felt like "home"), Modern ceremony (deep forest green and near-black, high-contrast serif, premium, closer to a tea house than a home café), and Sunlit café (terracotta and gold against sage, rounded serif, friendly, leaning into pop-up energy).' },
      { type: 'imageNote', heading: 'Style References', note: 'Looked at warm, food-forward brands and soft, handmade packaging for tone.' },
      { type: 'columns', heading: 'Building the System', items: [
        { title: 'Color', body: 'Warm, muted tones meant to feel like a home kitchen, not a café chain.' },
        { title: 'Type', body: 'A soft serif for warmth paired with a clean sans for labels and UI text.' },
        { title: 'Components', body: 'Recipe cards, order/pop-up states, and nav built to scale past matcha.' },
      ]},
      { type: 'features', heading: 'What It Does', items: [
        { title: 'Recipe Browsing', body: 'Browse an initial matcha recipe lineup by category.' },
        { title: 'Order Drop & Pop-Up Module', body: "Open, closed, and empty states, honest about what's actually live." },
        { title: 'Brand Story', body: 'The homepage carries the personal "why" behind Café Minty.' },
        { title: 'Real Photography', body: 'Original photography and a simple logo/wordmark, no stock or stand-ins.' },
      ]},
      { type: 'story', heading: 'What I killed', body: 'The homepage originally had a section called "Explore by category." Once it was built, it didn’t actually let anyone browse by category, it was just three cards. I killed the name and rebuilt the section as "Featured recipes," which described what it actually did.' },
      { type: 'beforeAfter', heading: 'Before Real Photography', title: 'Every recipe card started as a labeled placeholder slot. The brief pushed for real imagery everywhere, so nothing shipped until an actual photo replaced it.',
        beforeSrc: 'assets/cafeminty/recipes-page-before.webp', beforeAlt: 'Recipes page with placeholder image slots instead of photos',
        afterSrc: 'assets/cafeminty/screen-recipes-page.webp', afterAlt: 'Recipes page with real photography in place of the placeholder slots' },
      { type: 'divider', num: '02', kicker: 'Part Two', title: 'Exploration & Iteration' },
      { type: 'styleDirections',
        heading: 'Three directions, then a blend',
        directions: [
          { title: 'A: Terracotta / editorial serif', sub: 'Warm, food-forward, grounded', type: 'Georgia / system sans',
            palette: ['oklch(96% 0.012 80)', 'oklch(55% 0.13 40)', 'oklch(63% 0.09 140)', 'oklch(60% 0.09 65)', 'oklch(65% 0.09 5)'],
            verdict: 'What I already had. Safe and cohesive, reads as "café," but it played it straight and never felt like mine specifically.' },
          { title: 'B: Clay & sage / rounded serif', sub: 'Softer, friendlier, more handmade', type: 'Rounded slab serif / system sans',
            palette: ['oklch(96% 0.014 80)', 'oklch(60% 0.11 45)', 'oklch(64% 0.09 140)', 'oklch(76% 0.11 80)', 'oklch(68% 0.10 0)'],
            verdict: 'The rounded serif made it feel more handmade and personal, closer to "made by Martha" than "designed by a studio."' },
          { title: 'C: Charcoal & clay / high-contrast serif', sub: 'More minimal, closer to a design portfolio', type: 'High-contrast serif / mono-ish sans',
            palette: ['oklch(96% 0.012 80)', 'oklch(22% 0.008 60)', 'oklch(56% 0.13 40)', 'oklch(63% 0.09 140)', 'oklch(60% 0.09 65)'],
            verdict: 'The most minimal and editorial. Elevated, but risked feeling less warm and approachable for a food brand.' },
          { title: "D: A blend of B's warmth and C's structure", sub: 'Clay, sage & rose palette, sharper corners, quieter serif', chosen: true, type: 'Georgia serif, restrained tracking / system sans body',
            palette: ['oklch(96% 0.014 80)', 'oklch(22% 0.008 60)', 'oklch(60% 0.11 45)', 'oklch(64% 0.09 140)', 'oklch(68% 0.08 0)'],
            verdict: "B brings the warmth and human feel, C brings the restraint and structure, so it reads as designed, not soft. Charcoal became the primary action color throughout." },
        ],
        blendLogic: "One late change mattered more than it looked: I swapped the dessert accent from gold back to dusty rose. The gold sat too close to clay and matcha. All three read as “warm/food” and blurred together. Rose is cooler, so it separates cleanly as its own category. That locked the trio: sage for matcha, clay for coffee, dusty rose for dessert, on a cream and charcoal neutral base.",
      },
      { type: 'colorDecision',
        heading: 'Designing a palette that survives the menu growing',
        intro: "Café Minty launches matcha-first, but I knew from the start it wouldn't stay matcha-only. I plan to expand into coffee and desserts. So the real design question wasn't “what colors do I like,” it was: how do I build a visual system today that doesn't box me into a redesign later? I made the tradeoffs concrete by showing how each approach would actually handle matcha, coffee, and dessert side by side.",
        options: [
          { title: 'Neutral base, rotating accent', sub: 'Same bones, accent color signals category', chosen: true,
            verdict: "The color tells you what section you're in before you read a word, and a fourth category later means adding one accent, not rethinking the brand.",
            swatches: [
              { label: 'Matcha', color: 'oklch(62% 0.09 145)' },
              { label: 'Coffee', color: 'oklch(58% 0.11 50)' },
              { label: 'Dessert', color: 'oklch(68% 0.09 5)' },
            ]},
          { title: 'One signature color', sub: 'Ingredient-agnostic, color = you',
            verdict: 'Lowest maintenance and the most single-minded brand, but weak wayfinding: every category looks identical, so the palette does no navigational work.',
            swatches: [
              { label: 'Matcha', color: 'oklch(58% 0.11 50)' },
              { label: 'Coffee', color: 'oklch(58% 0.11 50)' },
              { label: 'Dessert', color: 'oklch(58% 0.11 50)' },
            ]},
          { title: 'Photography-led, near-neutral', sub: 'Let the food carry the color',
            verdict: "The most authentic option, but fragile. It only holds up as long as photo quality and consistency do, and that's a standard I'd have to hit on every single post.",
            swatches: [
              { label: 'Matcha', color: 'oklch(80% 0.02 90)' },
              { label: 'Coffee', color: 'oklch(80% 0.02 90)' },
              { label: 'Dessert', color: 'oklch(80% 0.02 90)' },
            ]},
        ],
        criteria: "I chose the rotating-accent system because it optimizes for the two things I cared about most: instant orientation for the customer, and extensibility. Adding a fourth category later means adding one new accent into an existing system.",
        tradeoff: "More ongoing color governance. Every new category's accent has to still feel cohesive with the others, so I'm treating the neutral base and typography as the fixed constraint that keeps it all reading as one brand.",
        close: "This mirrors how I approach product decisions at work. I don't just pick the option that looks best today; I think about what happens when the scope grows, because I've seen what it costs to retrofit a system that wasn't built to extend.",
      },
      { type: 'beforeAfter', heading: 'Iteration: The Headline',
        title: "Cut from four descriptive lines to one honest line, once the real “why” (loving to host) was clear. The nav also arrived here, so the page stopped floating.",
        beforeSrc: 'assets/cafeminty/headline-before.png', beforeAlt: 'Original hero: "Small-batch matcha, coffee, and desserts, made from a home kitchen, shared with the neighborhood."',
        afterSrc: 'assets/cafeminty/headline-after.png', afterAlt: 'Revised hero: "A little something, made for sharing."' },
      { type: 'beforeAfter', heading: 'Iteration: The Order Module',
        title: "The first version invented momentum: a live “This week's drop,” a scarcity line, a pop-up at a real market on a date I made up. It looked impressive and none of it was true. I replaced it with an honest empty state that keeps the section useful (“waiting on something sweet? so am I” + Notify me) instead of faking activity I couldn't deliver.",
        beforeSrc: 'assets/cafeminty/order-module-before.png', beforeAlt: 'Original "What\'s happening" module with a fabricated order drop and pop-up date',
        afterSrc: 'assets/cafeminty/order-module-after.png', afterAlt: 'Honest empty state: "waiting on something sweet? so am I" with a Notify me button' },
      { type: 'story', heading: "From Claude Design to Claude Code", body: "I built the first hi-fi version in Claude Design, then moved into Claude Code for the rest of the polish, real commits, real pushes to main, the kind of detail work a design tool alone doesn't cover." },
      { type: 'beforeAfter', heading: "Iteration: The “What's Happening” Background",
        title: "I asked for a background for this section and got four real options, not descriptions: a sage tint matching the header and footer, a washi-tape trim, the hero pattern reused, or a rose tint with the card flipped to white for contrast. I picked the rose tint. It reads as its own moment instead of blending into the rest of the page, and the order/pop-up cards were checked against it to make sure they still popped." },
      { type: 'story', heading: 'What I rejected', body: "I asked to move the mascot illustration so it wouldn't overlap the hero text on mobile. It got fixed properly, verified clean at three screen widths with no overlap and no horizontal scroll. I still didn't like how it looked and reverted it back to its original spot beside the photo. Technically correct isn't the same as right." },
      { type: 'imageNote', heading: 'The Mascot', note: "A small illustrated character used throughout the site, one more way it feels personal instead of templated.", images: [
        { src: 'assets/cafeminty/mascot-idle.webp', alt: 'Café Minty illustrated mascot, idle pose', caption: 'Idle' },
        { src: 'assets/cafeminty/mascot-wave.webp', alt: 'Café Minty illustrated mascot, waving', caption: 'Wave' },
      ]},
      { type: 'workingWithAI', heading: 'Where It Helped, Where It Didn’t', helped: [
        'Speeding up variations of homepage layout and component states.',
        'Drafting copy options to react to and cut down from.',
      ], fellShort: [
        "It read as too safe and quiet at first. Class crit, not AI, pushed the bolder direction.",
        "Needed my own judgment to know when a fix was technically correct but still not right, like the mascot placement.",
      ]},
      { type: 'divider', num: '03', kicker: 'Part Three', title: 'Usability Testing' },
      { type: 'story', heading: 'What I tested', body: 'I shared the live site with two different groups: a set of friends, including one with frontend development experience, and my class at crit.' },
      { type: 'features', heading: 'What Came Back', items: [
        { title: 'Nav order mismatch', body: 'Caught by a friend with frontend experience: the nav order (Recipes / Order / About) didn’t match the order sections actually appear on the homepage.' },
        { title: 'Placeholder images', body: 'Early placeholder images were making the site feel unfinished and less trustworthy.' },
        { title: 'Read as too safe', body: 'Class crit: the overall design read as too safe and quiet for a personal brand project.' },
        { title: '"About" page suggestion', body: 'Class crit suggested moving the About content to its own separate page.' },
      ]},
      { type: 'story', heading: 'What I changed', body: 'Reordered the nav to mirror the homepage’s real content flow, swapped every placeholder for real photography, and added a hero banner, washi tape detail, and an animated mascot to give the homepage more personality.' },
      { type: 'story', heading: "What I didn't act on", body: 'Moving "About" to its own page. The content is short enough that a separate page would just add an extra click with no real benefit, so I kept it on the homepage.' },
      { type: 'story', heading: 'What surprised me most', body: 'I’d been optimizing for a soft, quiet feel this whole project, assuming restraint was the right call for a personal brand. I hadn’t considered that "soft" could also read as "timid" until class crit pointed it out, the one piece of feedback that actually broke an assumption I was confident about.' },
      { type: 'divider', num: '04', kicker: 'Part Four', title: 'The Final Solution' },
      { type: 'imageNote', heading: 'Key Screens', note: 'Homepage, the recipe lineup, and the recipe grid, the final hi-fi build.', wide: true, images: [
        { src: 'assets/cafeminty/screen-hero.webp', alt: 'Café Minty homepage hero: "A little something, made for sharing."', caption: 'Homepage' },
        { src: 'assets/cafeminty/screen-homepage-featured.webp', alt: 'Café Minty homepage featured recipes section', caption: 'Featured Recipes' },
        { src: 'assets/cafeminty/screen-recipes-page.webp', alt: 'Café Minty Recipes page with category filter pills', caption: 'Recipes' },
        { src: 'assets/cafeminty/screen-recipes-footer.webp', alt: 'Café Minty "More matcha recipes" grid', caption: 'More Recipes' },
      ]},
      { type: 'reflectionBlock', quote: "Every real change pushed the same direction: toward less, but truer.", keepGoing: 'Open real ordering and expand the recipe lineup past matcha into coffee and desserts.', differently: "Would have scoped the order/pop-up module earlier. It drove most of the late-stage layout changes." },
    ],
  },
  {
    id: '3d',
    tag: '3D / Motion',
    title: 'BUBBLIPOP: 3D Modeling & Animation',
    blurb: 'Designing a fictional beverage can from a flat label to a modeled 3D object.',
    role: 'Solo, 3D Artist',
    timeline: '1 semester',
    tools: 'Canva, Blender, Unreal Engine',
    overview: "Bubblipop is a fictional beverage brand I'm designing from scratch, starting with the can label and building toward a full 3D model. It's a chance to get comfortable thinking in three dimensions instead of flat screens, and to carry one piece of branding all the way from a flat design file to a rendered object.",
    blocks: [
      { type: 'story', kicker: 'The Project', body: "Bubblipop, a fictional beverage brand, Strawberry Splash flavor. The goal is to take one piece of packaging all the way from a flat label design to a modeled, textured 3D can." },
      { type: 'imageNote', heading: 'The Label', wide: true, note: 'Designed first in Canva: the Bubblipop wordmark in a gradient sunset palette, a strawberry-splash illustration, bubbles, and sparkle accents, sized for a 16 fl oz can.', images: [
        { src: 'assets/3d/label-bubblipop-strawberry.png', alt: 'Bubblipop Strawberry Splash can label design made in Canva', caption: 'Strawberry Splash label' },
      ]},
      { type: 'story', heading: 'What I Did in Blender', body: "Started from a cylinder and built up the can's actual shape: beveled rims, a tapered top, and a modeled pull-tab lid instead of a flat cap. Unwrapped the UVs so the label would wrap around the body without stretching or seams showing, then applied the Canva label as a texture, all in Blender." },
      { type: 'columns', heading: 'The Workflow', items: [
        { title: '1. Base Geometry', body: 'Started from a cylinder, then beveled the rim edges and shaped the tapered top instead of leaving it perfectly sharp.' },
        { title: '2. Pull-Tab Detail', body: 'Modeled the lid separately with insets and extrusions to get a real pull-tab instead of a flat cap.' },
        { title: '3. UV Unwrapping', body: 'Marked seams and unwrapped the body into a flat rectangle so the label could wrap around it without stretching or visible seams.' },
        { title: '4. Label as Texture', body: 'Applied the Canva label as an image texture in Blender, mapped onto the unwrapped body.' },
        { title: '5. Materials', body: 'Refined the materials in Unreal Engine, tuning reflections and roughness until the aluminum body looked convincingly metal, plus a separate matte finish for the black variant test.' },
        { title: '6. Lighting & Render', body: 'Set up lighting and rendered the final and variant passes.' },
      ]},
      { type: 'imageNote', heading: 'The Process', wide: true, images: [
        { src: 'assets/3d/wireframe-blockout.png', alt: 'Wireframe of the base cylinder blockout for the can', caption: 'Base cylinder blockout' },
        { src: 'assets/3d/pulltab-wireframe-detail.webp', alt: 'Wireframe detail of the modeled pull-tab lid', caption: 'Modeling the pull-tab lid' },
        { src: 'assets/3d/shaded-can-shape.png', alt: 'Shaded view of the smoothed can shape with pull-tab top', caption: 'Smoothed can shape' },
        { src: 'assets/3d/uv-unwrap.webp', alt: 'UV unwrap layout next to the can wireframe', caption: 'UV unwrapping the body' },
        { src: 'assets/3d/material-test-black.webp', alt: 'Material test render of the can in a matte black finish', caption: 'Testing a matte black finish' },
        { src: 'assets/3d/final-render-label.webp', alt: 'Final render of the Bubblipop Strawberry Splash can with the label applied', caption: 'Final render, label applied' },
      ]},
      { type: 'story', heading: 'Unreal Engine: Materials & Animation', body: "Brought the finished model into Unreal Engine to push the materials further, tuning the aluminum body until it read as real metal instead of a flat gray shader, and to animate it for a short ad spot." },
      { type: 'video', heading: 'The Ad', note: 'The final animated spot for Bubblipop, rendered out of Unreal Engine.', src: 'assets/3d/bubblipop-ad.mp4' },
    ],
    reflection: "This project has no spec and no user to design for but myself, just a can I wanted to bring to life. Carrying one piece of branding across a 2D design tool and two different 3D tools is teaching me things about consistency, and about how a flat design decision has to hold up once it's wrapped around a real form.",
  },
  {
    id: 'scrapster',
    tag: 'AI / Mobile',
    title: 'Scrapster',
    blurb: 'Turning what’s already in your fridge into a meal before it becomes food waste.',
    role: 'Co-Designer & Engineer',
    timeline: '3 weeks',
    tools: 'Claude Design, Claude Code',
    liveUrl: 'https://claude.ai/artifact/1RsCtNdmnjaM6tkLtYc5gN',
    liveLabel: 'View Interactive Prototype',
    overview: "Scrapster is a mobile app that turns what's already in your fridge or pantry into a meal before it goes to waste. Snap a photo or type a list, and it builds one recipe around your most urgent ingredients first, instead of just filtering by a single ingredient like most food-waste apps.",
    reflection: "Built with a classmate over three weeks in Claude Design and Claude Code, going from product brief straight to a full interactive prototype.",
    blocks: [
      { type: 'story', kicker: 'The Problem', body: "Busy students and young professionals let food go to waste, not from carelessness, but because turning random leftovers into an actual meal takes mental effort they don't have time for between class, work, and unpredictable schedules. It hits hardest as wasted money on a tight budget, plus daily decision fatigue on top of an already full plate." },
      { type: 'story', kicker: "Who It's For", body: "Students and young professionals, roughly 18 to 30, living alone or with roommates and cooking for one or two. Tight budgets where wasted food actually stings, and unpredictable schedules that lead to forgotten groceries." },
      { type: 'story', kicker: 'My Role', body: 'Co-designer and engineer, working with a classmate over three weeks, from product brief to a full interactive prototype in Claude Design and Claude Code.' },
      { type: 'story', heading: 'The Solution', body: "You input what you have, a photo of your fridge or pantry, or a typed list, and it builds a simple, low-equipment recipe around your most urgent ingredients first (the wilting spinach before the shelf-stable rice), combining several small leftovers into one dish instead of just filtering by a single ingredient." },
      { type: 'divider', num: '01', kicker: 'Part One', title: 'What It Does' },
      { type: 'features', heading: 'Core Features', items: [
        { title: 'Flexible Input', body: 'A photo of your fridge or pantry, a grocery receipt scan, or a typed list.' },
        { title: 'Urgency-Ranked Recipes', body: 'Combines the most urgent ingredients into one recipe instead of matching a single item.' },
        { title: 'Budget Mode', body: "Shows the cheapest place to grab whatever the recipe is still missing." },
        { title: 'Leftover Chaining', body: "Remembers what you cooked and suggests the next meal from what's left." },
        { title: 'Savings Tracker', body: 'A running total of money and food saved over time.' },
      ]},
      { type: 'story', heading: 'How AI Does the Real Work', body: "It's not a database lookup: it parses a blurry photo or a casual list, ranks ingredients by how soon they'll spoil, and reasons across several odds-and-ends to find one recipe that plausibly unifies them, not just the closest single-ingredient match." },
      { type: 'story', heading: 'The Differentiator', body: "Apps like SuperCook and Yummly match ingredients to recipes. Scrapster prioritizes by urgency and combination, defaults to simple, low-equipment recipes for this user's actual kitchen, and closes the loop with a visible savings and waste-reduced tracker." },
      { type: 'divider', num: '02', kicker: 'Part Two', title: 'Design Options & Iterations' },
      { type: 'imageNote', heading: 'Typography & Tone', wide: true, note: "Explored four directions for the same post-scan home screen, where urgency ranking and the savings number both have to land: Pantry Paper (Instrument Serif + IBM Plex Sans, reads like a cookbook, warmest and least “app-y”), Night Kitchen (Archivo Black + IBM Plex Mono, poster-weight and the most screenshot-able for social), Fresh Grocer (Space Grotesk alone, safest and fastest to build, but risks looking like every other wellness app), and Expiry Ticket (Bricolage Grotesque + IBM Plex Mono, where color itself carries the urgency meaning, the boldest direction to commit to). Fresh Grocer is the one the rest of the screens were built in.", images: [
        { src: 'assets/scrapster/typography-1a-1b-1c.webp', alt: 'Three theme and typography directions for the Scrapster home screen: Pantry Paper, Night Kitchen, and Fresh Grocer', caption: 'Pantry Paper, Night Kitchen, and Fresh Grocer' },
      ]},
      { type: 'story', heading: 'Onboarding: Three Ways In', body: "Each option is the sign-up screen plus how the diet and allergy questions follow it, since the two have to feel like one move. Straight ahead is a conventional form with diet as a skippable step: lowest risk, but a wall of form before the app has proven anything. Proof first leads with a savings stat before asking for any signup info: best for a campus launch, riskier if the stat can't be sourced honestly. No password sends an email code and learns diet from a first real food choice: least friction, but allergies still have to be typed in words, since those can't be safely guessed." },
      { type: 'imageNote', heading: 'The Homescreen: What Wins the Top', wide: true, note: "All three versions kept the same two required elements, the “what do you have” prompt and the running savings widget, but disagreed on which one wins the top of the screen. Tracker on top matches the brief literally, but the primary action sits below a card you've already read a hundred times. Camera-led treats the app as a single button and demotes savings to a strip, fastest to the core loop, but on a slow day it feels like a camera, not a companion. Urgency-led opens already knowing what's about to go bad and answers “what's for dinner” before you ask, the most differentiated option, but it needs a real first-run state for day one.", images: [
        { src: 'assets/scrapster/homescreen-options.webp', alt: 'Three homescreen options: tracker on top, camera-led, and urgency-led', caption: 'Tracker on top, camera-led, and urgency-led' },
      ]},
      { type: 'story', heading: 'Ingredient Confirmation: Fixing What the AI Got Wrong', body: "The correction moment: parsed ingredients, editable, with urgency flagged before any recipe is generated. All three let you fix a misread and all three show confidence, they differ in whether you're editing a cloud of chips, reviewing the photo, or triaging by deadline. The chip field is densest and quickest, and a dashed “Kale? Spinach?” chip makes the AI's uncertainty a normal, tappable thing, but chips can't carry quantities. Photo review is the most trustworthy, boxes on the photo prove the AI looked, but it's the longest screen and needs real detection output. Deadline triage is the most on-message, putting a dollar value on each expiring item, but price estimates can be wrong and drag-to-reorder is fussy on mobile." },
      { type: 'imageNote', heading: 'Recipe Results: How Much Choosing to Ask For', wide: true, note: "The real question here wasn't which layout looked best, it was how much choosing to make the user do, since the whole app exists to kill decision fatigue. A ranked list has the clearest hierarchy, but looks like every recipe list. One answer commits and explains why in a sentence, the most true to the problem, but if the single pick is wrong twice in a row, trust drops fast. The trade-off view makes the ranking logic legible, but has no photos and asks the user to compare, which is the fatigue we're trying to remove.", images: [
        { src: 'assets/scrapster/recipe-results-options.webp', alt: 'Three recipe result options: ranked list, one answer, and trade-off view', caption: 'Ranked list, one answer, and trade-off view' },
      ]},
      { type: 'story', heading: 'Cook Mode: Checklist vs. One Step at a Time', body: "The last screen of the loop is the steps plus the “mark as cooked” moment that fires leftover chaining and bumps the tracker. The checklist is the safest build: one scrollable screen, ticking is optional, and the payoff screen does the emotional work, but it's awkward on a phone propped against a kettle with wet hands. The one-step mode is best while actually cooking, big type on a dark screen with one instruction at arm's length, and the leftover capture happens right after eating when the answer is known. The cost is two modes to build, and a confirmation that asks for input at the laziest moment of the night." },
      { type: 'story', heading: 'What Made It Into the Prototype', body: "The prototype leaned on the safer builds: the Fresh Grocer theme, a tracker-on-top home screen, the single decided answer (\u201cTonight, decided\u201d) for recipe results, and the checklist for cooking. Ingredient confirmation changed the most. It ended up as a merge review, \u201cNew since Sunday,\u201d that reconciles a new scan against what's already in the kitchen list, rather than any of the three options above." },
      { type: 'divider', num: '03', kicker: 'Part Three', title: 'Decisions & Tradeoffs' },
      { type: 'story', heading: 'The Kitchen We Designed For', body: "One open question we had to settle as a team: does the app assume a dorm-style kitchen (microwave, mini-fridge, maybe a hot plate) or a first-apartment kitchen (stove, oven)? We picked first-apartment, so recipes can assume standard stovetop and oven equipment instead of hedging for both." },
      { type: 'story', heading: 'Matching the Prototype, Not a Narrower Cut', body: "The original plan was a narrower first version: flexible input, urgency ranking, and one recipe, deferring budget mode, personalization, leftover chaining, and the tracker. Once the full Claude Design prototype existed end to end, we chose to build toward that instead of re-splitting the scope." },
      { type: 'divider', num: '04', kicker: 'Part Four', title: 'Where It Stands' },
      { type: 'imageNote', heading: 'Key Screens', cols3: true, note: 'Six screens from the prototype that make up the core loop, from adding what you have to seeing what it saved. The full app has eleven, ported from this Claude Design prototype into React Native.', images: [
        { src: 'assets/scrapster/prototype-home.webp', alt: 'Scrapster home screen with monthly savings, kitchen status, and ways to add what you have', caption: 'Home' },
        { src: 'assets/scrapster/prototype-confirm-new-since-sunday.webp', alt: 'Scrapster review screen showing a new scan merged against the existing kitchen list', caption: 'Confirm a new scan' },
        { src: 'assets/scrapster/prototype-kitchen-list.webp', alt: 'Scrapster kitchen list grouped by urgency: use now, this week, keeps a while', caption: 'Your kitchen, by urgency' },
        { src: 'assets/scrapster/prototype-recipe-result.webp', alt: 'Scrapster recipe result showing one decided dish with time, ingredients used, and cost to finish', caption: 'Tonight, decided' },
        { src: 'assets/scrapster/prototype-cook-steps.webp', alt: 'Scrapster step-by-step cooking checklist with ingredients pulled from the kitchen list', caption: 'Cook it' },
        { src: 'assets/scrapster/prototype-saved-tracker.webp', alt: 'Scrapster savings tracker with lifetime savings, monthly chart, and a personalized insight', caption: 'Your scraps, counted' },
      ]},
      { type: 'story', heading: "What's Real vs. Mocked", body: "All eleven screens are built and running on the exact interaction model from the Claude Design prototype, currently on mock data. The backend already does the real AI work, photo and list parsing, urgency ranking, and recipe generation through Claude, it's just not wired into the mobile app's scan flow yet. Login, budget-mode pricing, and the savings tracker's history are still UI-only." },
      { type: 'story', heading: "What's Next", body: "Wiring the mobile scan flow to the real backend instead of the canned demo data, then real auth, a grocery-price source for Budget mode, and a persistent savings ledger." },
    ],
  },
];
