// Portfolio content, ported from the Claude Design canvas artifact.
const PROJECTS = [
  {
    id: 'jpmc',
    tag: 'Enterprise Tool',
    title: 'JPMC Corporate Challenge: Report Hub',
    blurb: 'Redesigning how stakeholders track, and share event reports.',
    role: 'Product Management',
    timeline: '10 weeks',
    tools: 'Jira, Confluence',
    overview: "Reporting is critical to running JPMC's global Corporate Challenge events. It's how Admins and Local Race Organizers manage thousands of company teams and participant logistics across 16 cities. The existing reports ran on AWS QuickSight, but with CCB support for that platform ending, staying on it created a security and compliance risk. I led product management for the migration to a custom-built reporting solution.",
    sections: [
      { heading: 'The Problem', body: "QuickSight support was being sunset, and alternatives like Tableau ran into external-access constraints for our user base. We needed a path that kept reporting supported, secure, and accessible to business users, without losing what Admins and Local Race Organizers relied on day to day." },
      { heading: 'The Approach', body: "I scoped the work around getting our core business users (OBE Administrators and Local Race Organizers, or LROs) access to the reports and data they needed for day-to-day operations, so nothing broke on cutover." },
      { heading: 'Delivery & Readiness', body: "A focused team of 3 technologists worked through the business requirements and delivered a custom replacement for the existing reporting suite in 5 sprints, with full delivery automation so future changes could ship without any external dependency. Product, Tech, and DCE completed validations to support a smooth launch, with close monitoring as usage ramped up. We also leaned on AI tooling (Copilot) for UI scaffolding, test/load testing, and synthetic data generation, for an estimated ~50% improvement in delivery productivity." },
      { heading: 'The Outcome', body: "Report Hub is now live for OBE Administrators and Local Race Organizers across all 16 cities, delivering real-time data through a supported, secure, custom-built home for reporting fully off QuickSight, saving an estimated $25K a year." },
    ],
    reflection: "This was my first time owning a migration end-to-end rather than a single feature. Scoping the work around what business users actually needed forced me to get comfortable saying 'not yet' to nice-to-haves so the essentials shipped on time, a tradeoff I now default to on every roadmap.",
  },
  {
    id: 'closet',
    tag: 'Mobile App',
    title: 'ClosetMind: Mindful Wardrobe App',
    blurb: 'Helping people build outfits from clothes they already own.',
    role: 'UX Designer & Engineer',
    timeline: '1 semester',
    tools: 'Claude Design, Claude Code',
    overview: 'ClosetMind is a mobile app that helps people rediscover and wear the clothes they already own. Tagline: your wardrobe, archived. Designed for my Principles of Digital Design course, this was the first project where I owned the full process myself: research, definition, design, and testing.',
    reflection: "This was my first project built entirely from my own research instead of a client brief, which meant I couldn't lean on anyone else's assumptions about the user. It pushed me to trust, and then test, my own instincts.",
    blocks: [
      { type: 'story', kicker: 'The Problem', body: "Most people wear 20% of their wardrobe 80% of the time. The rest gets forgotten behind the clothes that happen to be at the front. ClosetMind gives people a way to catalog what they own, resurface pieces they've stopped thinking about, and make outfit decisions with confidence, without buying anything new." },
      { type: 'quote', kicker: 'Research', quote: "The recurring theme wasn't a lack of clothes, it was a lack of visibility into what they already had.", points: [
        'Interviewed 4 friends and target users about how they currently plan outfits.',
        "Every one of them described the same loop: stand in front of the closet, can't decide, default to buying something new.",
        'That loop reframed the problem: how might we help someone see their wardrobe as a set of possible outfits, not a pile of individual items?',
      ]},
      { type: 'story', kicker: "Who It's For", body: "The target user is someone with a full wardrobe who still feels like they have nothing to wear." },
      { type: 'divider', kicker: 'Part One', title: 'Design System' },
      { type: 'columns', heading: 'Building the System', items: [
        { title: 'Color', body: 'Near-black and warm off-white, high contrast, editorial rather than app-y.' },
        { title: 'Type', body: 'A serif for screen titles, paired with a small-caps sans for labels.' },
        { title: 'Components', body: 'Filter pills, favoritable cards, a five-tab nav, and consistent black buttons throughout.' },
      ]},
      { type: 'divider', kicker: 'Part Two', title: 'Features' },
      { type: 'features', heading: 'What It Does', items: [
        { title: "Today's Suggestion", body: "A daily outfit recommendation pulled from the user's wardrobe, with a full detail view." },
        { title: 'Wardrobe Catalog', body: 'Grid view with filters, individual item detail, and the ability to edit or delete pieces.' },
        { title: 'Saved Outfits', body: 'Organized into folders, with an outfit grid and a detail view that lists every piece.' },
        { title: 'Build Outfit', body: 'Manually assemble an outfit from wardrobe pieces using a live selection flow.' },
        { title: 'Outfit Diary (Inspo)', body: 'Two tabs: saved looks from external inspiration, and created looks the user has logged.' },
        { title: "Log Today's Outfit", body: 'Quick capture of what you actually wore, feeding the diary.' },
        { title: 'Mira', body: 'An AI style assistant available as a chat screen for style questions and recommendations.' },
        { title: 'Auth Flows', body: 'Sign in, create account, and a three-step forgot password flow.' },
      ]},
      { type: 'divider', kicker: 'Part Three', title: 'Design Approach' },
      { type: 'story', heading: 'An editorial-first system', body: 'ClosetMind is designed editorial-first, with an aesthetic that feels more like a fashion archive than a utility app. The process started with competitive analysis and "how might we" framing, then moved to building a design system before touching any screens. Each screen was designed with options at key decision points, validated through informal user testing, and iterated from there.' },
      { type: 'story', heading: 'A deliberate restraint', body: 'The profile screen is deliberately minimal. No stats, no gamification. The focus stays on the clothes.' },
      { type: 'divider', kicker: 'Part Four', title: 'Working With Claude' },
      { type: 'workingWithAI', heading: 'What Claude Was Good For', helped: [
        'Scaffolding screens and component states quickly in Claude Design, so more time went into the flows and copy than into rebuilding basic UI from scratch.',
      ], fellShort: [
        "It couldn't tell me whether a pattern would actually make sense to someone who'd never used the app before. That only surfaced once real people tried it, which is exactly what usability testing caught." ,
      ]},
      { type: 'divider', kicker: 'Part Five', title: 'Usability Testing' },
      { type: 'story', heading: 'What I tested', body: "I walked four people through the ClosetMind prototype (design-only, no backend): a product manager, a software engineer, my target user, and a design mentor. Each ran the core flows unmoderated, at their own pace, adding a piece, matching an inspo photo, generating an outfit, and saving a look." },
      { type: 'features', heading: 'What worked', items: [
        { title: 'Instant clarity', body: 'Every tester understood the concept from the first screen. No explanation needed.' },
        { title: "Today's Suggestion wins", body: 'Two testers tapped it first when looking for an outfit, confirming it as the strongest entry point.' },
        { title: 'Alternatives read clearly', body: 'The alternatives-and-checkmarks pattern mapped instantly to "what I own vs. what I’d need."' },
        { title: 'Daily-use potential', body: "One tester said they'd use it daily, especially while traveling." },
      ]},
      { type: 'columns', heading: "What I'd change next", items: [
        { title: 'No detail view', body: "Today's Suggestion doesn't open one yet. Both non-designer testers expected it to." },
        { title: 'No onboarding', body: 'Rediscover needs a tooltip or empty state before a user has wardrobe history.' },
        { title: 'Stay free', body: "One tester said cost would be a dealbreaker, a signal to design this free, not to add a paywall later." },
      ]},
      { type: 'divider', kicker: 'Part Six', title: 'The Final Solution' },
      { type: 'imageNote', heading: 'Key Screens', note: 'Home, Wardrobe, Item Detail, Inspo, Mira, and Profile, the editorial-first system carried across every screen.', images: [
        { src: 'assets/closetmind/home.png', alt: 'ClosetMind Home screen', caption: 'Home' },
        { src: 'assets/closetmind/wardrobe.png', alt: 'ClosetMind Wardrobe catalog grid', caption: 'Wardrobe' },
        { src: 'assets/closetmind/item-detail.png', alt: 'ClosetMind item detail screen', caption: 'Item Detail' },
        { src: 'assets/closetmind/inspo-grid.png', alt: 'ClosetMind Inspo grid', caption: 'Inspo' },
        { src: 'assets/closetmind/inspo-detail.png', alt: 'ClosetMind Inspo detail with matched pieces from the wardrobe', caption: 'Inspo Detail: Matched Pieces' },
        { src: 'assets/closetmind/mira.png', alt: 'ClosetMind Mira AI style assistant chat', caption: 'Mira' },
        { src: 'assets/closetmind/profile.png', alt: 'ClosetMind Profile screen', caption: 'Profile' },
      ]},
      { type: 'imageNote', heading: 'Flow Walkthrough', note: 'Adding a piece to the wardrobe: tap the + on Home, choose how to add it (photo, barcode scan, or a pasted link), then land on Item Detail to confirm name, brand, category, size, and color.', images: [
        { src: 'assets/closetmind/home.png', alt: 'Home screen with add button', caption: '1. Tap + on Home' },
        { src: 'assets/closetmind/add-item.png', alt: 'Add to your wardrobe modal', caption: '2. Choose how to add it' },
        { src: 'assets/closetmind/item-detail.png', alt: 'Item detail confirmation screen', caption: '3. Confirm the details' },
      ]},
      { type: 'story', kicker: 'Outcome & Impact', body: "ClosetMind is currently a design-only prototype, no backend or database, built and tested in Claude Design and Claude Code. Across four usability sessions the core concept validated cleanly: every tester understood the value within seconds, and the target user confirmed it solves a problem she actually has. The clearest open threads are a detail view for Today's Suggestion, onboarding for first-time users, and deeper wardrobe organization (categories, filters, style tags) that came up as the most-requested next step." },
      { type: 'reflectionBlock', quote: "Trust it, then test it: that's the only instinct worth keeping.", keepGoing: "Add a detail view for Today's Suggestion, onboarding for first-time users, and richer wardrobe organization (categories, filters, style tags).", differently: "I'd capture process artifacts, sketches, style references, iteration rounds, as I went instead of reconstructing them afterward. A portfolio review made it clear how much stronger the story reads when that thinking is documented in the moment, not after the fact." },
    ],
  },
  {
    id: 'cafeminty',
    tag: 'Brand & Web',
    title: 'Café Minty',
    blurb: 'A personal brand hub for the matcha and desserts I make at home.',
    role: 'Solo, Brand & UX/UI Designer',
    timeline: 'Weeks 12–15, 1 semester',
    tools: 'Claude Design, Claude Code',
    liveUrl: 'https://cafe-minty.netlify.app/',
    overview: "Café Minty is a unified brand hub for a home café idea I've had for a while but never built: a place to share matcha recipes, and eventually give people a real way to try what I make, through an order drop or pop-up. It launches matcha-first but is designed as a system that can expand into coffee, desserts, and whatever comes next, without needing a redesign.",
    reflection: "Building something I'd only ever thought about, rather than a class-assigned brief, forced me to define my own scope and know when to stop polishing and ship. Class crit pushing me to be bolder, and my own instinct to cut what wasn't real yet, were both lessons in trusting a point of view.",
    blocks: [
      { type: 'story', kicker: 'Product Story', body: "I love making matcha at home, and I've always loved hosting and feeding people, but this idea has only ever lived in my head. This project was my chance to actually build it for the first time: to figure out what it looks like, how it should feel, and whether it's something I'd genuinely want to keep going after the semester ends." },
      { type: 'story', kicker: "Who It's For", body: "Right now, friends and family who see something I post on my personal Instagram and DM me asking how to make it. But it's built for anyone who finds my content, and eventually, local customers who want to order or catch a pop-up." },
      { type: 'story', kicker: 'The Value', body: "Once Café Minty exists, that same audience gets a place to actually find and return to recipes, instead of a one-off DM reply, and longer-term, a real way to order or catch a pop-up." },
      { type: 'story', kicker: 'My Role', body: 'Solo, brand and UX/UI design, weeks 12–15 of the semester, built in Claude Design and Claude Code, with original photography.' },
      { type: 'quote', quote: "I love making culturally-rooted drinks and desserts, but I have no diary-like place to even remember my own recipes, let alone somewhere for others to find them or know about a future order drop or pop-up.", points: [
        "Instagram can't hold recipes people return to.",
        "No way for anyone to actually order or find out about a pop-up.",
        "The idea only ever lived in my head, never had a real shape.",
      ]},
      { type: 'audience', heading: 'The Audience', cards: [
        { title: 'Friends & Family', body: "The first audience: people already DMing me for recipes off my personal Instagram." },
        { title: 'Content Followers', body: "Anyone who finds Café Minty through content I share, even without a prior connection to me." },
        { title: 'Local Customers', body: "Longer-term: people discovering it through a real pop-up or order drop." },
      ]},
      { type: 'divider', num: '01', kicker: 'Part One', title: 'Thinking & Process' },
      { type: 'story', heading: 'Three early directions', body: 'Before locking any system, I explored three overall moods: Matcha garden (soft sage and cream, editorial serif, safe and cohesive, felt like "home"), Modern ceremony (deep forest green and near-black, high-contrast serif, premium, closer to a tea house than a home café), and Sunlit café (terracotta and gold against sage, rounded serif, friendly, leaning into pop-up energy).' },
      { type: 'imageNote', heading: 'Style References', note: 'Looked at warm, food-forward brands and soft, handmade packaging for tone.' },
      { type: 'columns', heading: 'Building the System', items: [
        { title: 'Color', body: 'Warm, muted tones meant to feel like a home kitchen, not a café chain.' },
        { title: 'Type', body: 'A soft serif for warmth paired with a clean sans for labels and UI text.' },
        { title: 'Components', body: 'Recipe cards, order/pop-up states, and nav built to scale past matcha.' },
      ]},
      { type: 'features', heading: 'What It Does', items: [
        { title: 'Recipe Browsing', body: 'Browse an initial matcha recipe lineup by category.' },
        { title: 'Order Drop & Pop-Up Module', body: "Open, closed, and empty states, honest about what's actually live." },
        { title: 'Brand Story', body: 'The homepage carries the personal "why" behind Café Minty.' },
        { title: 'Real Photography', body: 'Original photography and a simple logo/wordmark, no stock or stand-ins.' },
      ]},
      { type: 'story', heading: 'What I killed', body: 'The homepage originally had a section called "Explore by category." Once it was built, it didn’t actually let anyone browse by category, it was just three cards. I killed the name and rebuilt the section as "Featured recipes," which described what it actually did.' },
      { type: 'beforeAfter', heading: 'Before Real Photography', title: 'Every recipe card started as a labeled placeholder slot. The brief pushed for real imagery everywhere, so nothing shipped until an actual photo replaced it.',
        beforeSrc: 'assets/cafeminty/recipes-page-before.webp', beforeAlt: 'Recipes page with placeholder image slots instead of photos',
        afterSrc: 'assets/cafeminty/screen-recipes-page.webp', afterAlt: 'Recipes page with real photography in place of the placeholder slots' },
      { type: 'divider', num: '02', kicker: 'Part Two', title: 'Exploration & Iteration' },
      { type: 'styleDirections',
        heading: 'Three directions, then a blend',
        directions: [
          { title: 'A: Terracotta / editorial serif', sub: 'Warm, food-forward, grounded', type: 'Georgia / system sans',
            palette: ['oklch(96% 0.012 80)', 'oklch(55% 0.13 40)', 'oklch(63% 0.09 140)', 'oklch(60% 0.09 65)', 'oklch(65% 0.09 5)'],
            verdict: 'What I already had. Safe and cohesive, reads as "café," but it played it straight and never felt like mine specifically.' },
          { title: 'B: Clay & sage / rounded serif', sub: 'Softer, friendlier, more handmade', type: 'Rounded slab serif / system sans',
            palette: ['oklch(96% 0.014 80)', 'oklch(60% 0.11 45)', 'oklch(64% 0.09 140)', 'oklch(76% 0.11 80)', 'oklch(68% 0.10 0)'],
            verdict: 'The rounded serif made it feel more handmade and personal, closer to "made by Martha" than "designed by a studio."' },
          { title: 'C: Charcoal & clay / high-contrast serif', sub: 'More minimal, closer to a design portfolio', type: 'High-contrast serif / mono-ish sans',
            palette: ['oklch(96% 0.012 80)', 'oklch(22% 0.008 60)', 'oklch(56% 0.13 40)', 'oklch(63% 0.09 140)', 'oklch(60% 0.09 65)'],
            verdict: 'The most minimal and editorial. Elevated, but risked feeling less warm and approachable for a food brand.' },
          { title: "D: A blend of B's warmth and C's structure", sub: 'Clay, sage & rose palette, sharper corners, quieter serif', chosen: true, type: 'Georgia serif, restrained tracking / system sans body',
            palette: ['oklch(96% 0.014 80)', 'oklch(22% 0.008 60)', 'oklch(60% 0.11 45)', 'oklch(64% 0.09 140)', 'oklch(68% 0.08 0)'],
            verdict: "B brings the warmth and human feel, C brings the restraint and structure, so it reads as designed, not soft. Charcoal became the primary action color throughout." },
        ],
        blendLogic: "One late change mattered more than it looked: I swapped the dessert accent from gold back to dusty rose. The gold sat too close to clay and matcha. All three read as “warm/food” and blurred together. Rose is cooler, so it separates cleanly as its own category. That locked the trio: sage for matcha, clay for coffee, dusty rose for dessert, on a cream and charcoal neutral base.",
      },
      { type: 'colorDecision',
        heading: 'Designing a palette that survives the menu growing',
        intro: "Café Minty launches matcha-first, but I knew from the start it wouldn't stay matcha-only. I plan to expand into coffee and desserts. So the real design question wasn't “what colors do I like,” it was: how do I build a visual system today that doesn't box me into a redesign later? I made the tradeoffs concrete by showing how each approach would actually handle matcha, coffee, and dessert side by side.",
        options: [
          { title: 'Neutral base, rotating accent', sub: 'Same bones, accent color signals category', chosen: true,
            verdict: "The color tells you what section you're in before you read a word, and a fourth category later means adding one accent, not rethinking the brand.",
            swatches: [
              { label: 'Matcha', color: 'oklch(62% 0.09 145)' },
              { label: 'Coffee', color: 'oklch(58% 0.11 50)' },
              { label: 'Dessert', color: 'oklch(68% 0.09 5)' },
            ]},
          { title: 'One signature color', sub: 'Ingredient-agnostic, color = you',
            verdict: 'Lowest maintenance and the most single-minded brand, but weak wayfinding: every category looks identical, so the palette does no navigational work.',
            swatches: [
              { label: 'Matcha', color: 'oklch(58% 0.11 50)' },
              { label: 'Coffee', color: 'oklch(58% 0.11 50)' },
              { label: 'Dessert', color: 'oklch(58% 0.11 50)' },
            ]},
          { title: 'Photography-led, near-neutral', sub: 'Let the food carry the color',
            verdict: "The most authentic option, but fragile. It only holds up as long as photo quality and consistency do, and that's a standard I'd have to hit on every single post.",
            swatches: [
              { label: 'Matcha', color: 'oklch(80% 0.02 90)' },
              { label: 'Coffee', color: 'oklch(80% 0.02 90)' },
              { label: 'Dessert', color: 'oklch(80% 0.02 90)' },
            ]},
        ],
        criteria: "I chose the rotating-accent system because it optimizes for the two things I cared about most: instant orientation for the customer, and extensibility. Adding a fourth category later means adding one new accent into an existing system.",
        tradeoff: "More ongoing color governance. Every new category's accent has to still feel cohesive with the others, so I'm treating the neutral base and typography as the fixed constraint that keeps it all reading as one brand.",
        close: "This mirrors how I approach product decisions at work. I don't just pick the option that looks best today; I think about what happens when the scope grows, because I've seen what it costs to retrofit a system that wasn't built to extend.",
      },
      { type: 'beforeAfter', heading: 'Iteration: The Headline',
        title: "Cut from four descriptive lines to one honest line, once the real “why” (loving to host) was clear. The nav also arrived here, so the page stopped floating.",
        beforeSrc: 'assets/cafeminty/headline-before.png', beforeAlt: 'Original hero: "Small-batch matcha, coffee, and desserts, made from a home kitchen, shared with the neighborhood."',
        afterSrc: 'assets/cafeminty/headline-after.png', afterAlt: 'Revised hero: "A little something, made for sharing."' },
      { type: 'beforeAfter', heading: 'Iteration: The Order Module',
        title: "The first version invented momentum: a live “This week's drop,” a scarcity line, a pop-up at a real market on a date I made up. It looked impressive and none of it was true. I replaced it with an honest empty state that keeps the section useful (“waiting on something sweet? so am I” + Notify me) instead of faking activity I couldn't deliver.",
        beforeSrc: 'assets/cafeminty/order-module-before.png', beforeAlt: 'Original "What\'s happening" module with a fabricated order drop and pop-up date',
        afterSrc: 'assets/cafeminty/order-module-after.png', afterAlt: 'Honest empty state: "waiting on something sweet? so am I" with a Notify me button' },
      { type: 'story', heading: "From Claude Design to Claude Code", body: "I built the first hi-fi version in Claude Design, then moved into Claude Code for the rest of the polish, real commits, real pushes to main, the kind of detail work a design tool alone doesn't cover." },
      { type: 'beforeAfter', heading: "Iteration: The “What's Happening” Background",
        title: "I asked for a background for this section and got four real options, not descriptions: a sage tint matching the header and footer, a washi-tape trim, the hero pattern reused, or a rose tint with the card flipped to white for contrast. I picked the rose tint. It reads as its own moment instead of blending into the rest of the page, and the order/pop-up cards were checked against it to make sure they still popped." },
      { type: 'story', heading: 'What I rejected', body: "I asked to move the mascot illustration so it wouldn't overlap the hero text on mobile. It got fixed properly, verified clean at three screen widths with no overlap and no horizontal scroll. I still didn't like how it looked and reverted it back to its original spot beside the photo. Technically correct isn't the same as right." },
      { type: 'imageNote', heading: 'The Mascot', note: "A small illustrated character used throughout the site, one more way it feels personal instead of templated.", images: [
        { src: 'assets/cafeminty/mascot-idle.webp', alt: 'Café Minty illustrated mascot, idle pose', caption: 'Idle' },
        { src: 'assets/cafeminty/mascot-wave.webp', alt: 'Café Minty illustrated mascot, waving', caption: 'Wave' },
      ]},
      { type: 'workingWithAI', heading: 'Where It Helped, Where It Didn’t', helped: [
        'Speeding up variations of homepage layout and component states.',
        'Drafting copy options to react to and cut down from.',
      ], fellShort: [
        "It read as too safe and quiet at first. Class crit, not AI, pushed the bolder direction.",
        "Needed my own judgment to know when a fix was technically correct but still not right, like the mascot placement.",
      ]},
      { type: 'divider', num: '03', kicker: 'Part Three', title: 'Usability Testing' },
      { type: 'story', heading: 'What I tested', body: 'I shared the live site with two different groups: a set of friends, including one with frontend development experience, and my class at crit.' },
      { type: 'features', heading: 'What Came Back', items: [
        { title: 'Nav order mismatch', body: 'Caught by a friend with frontend experience: the nav order (Recipes / Order / About) didn’t match the order sections actually appear on the homepage.' },
        { title: 'Placeholder images', body: 'Early placeholder images were making the site feel unfinished and less trustworthy.' },
        { title: 'Read as too safe', body: 'Class crit: the overall design read as too safe and quiet for a personal brand project.' },
        { title: '"About" page suggestion', body: 'Class crit suggested moving the About content to its own separate page.' },
      ]},
      { type: 'story', heading: 'What I changed', body: 'Reordered the nav to mirror the homepage’s real content flow, swapped every placeholder for real photography, and added a hero banner, washi tape detail, and an animated mascot to give the homepage more personality.' },
      { type: 'story', heading: "What I didn't act on", body: 'Moving "About" to its own page. The content is short enough that a separate page would just add an extra click with no real benefit, so I kept it on the homepage.' },
      { type: 'story', heading: 'What surprised me most', body: 'I’d been optimizing for a soft, quiet feel this whole project, assuming restraint was the right call for a personal brand. I hadn’t considered that "soft" could also read as "timid" until class crit pointed it out, the one piece of feedback that actually broke an assumption I was confident about.' },
      { type: 'divider', num: '04', kicker: 'Part Four', title: 'The Final Solution' },
      { type: 'imageNote', heading: 'Key Screens', note: 'Homepage, the recipe lineup, and the recipe grid, the final hi-fi build.', wide: true, images: [
        { src: 'assets/cafeminty/screen-hero.webp', alt: 'Café Minty homepage hero: "A little something, made for sharing."', caption: 'Homepage' },
        { src: 'assets/cafeminty/screen-homepage-featured.webp', alt: 'Café Minty homepage featured recipes section', caption: 'Featured Recipes' },
        { src: 'assets/cafeminty/screen-recipes-page.webp', alt: 'Café Minty Recipes page with category filter pills', caption: 'Recipes' },
        { src: 'assets/cafeminty/screen-recipes-footer.webp', alt: 'Café Minty "More matcha recipes" grid', caption: 'More Recipes' },
      ]},
      { type: 'reflectionBlock', quote: "Every real change pushed the same direction: toward less, but truer.", keepGoing: 'Open real ordering and expand the recipe lineup past matcha into coffee and desserts.', differently: "Would have scoped the order/pop-up module earlier. It drove most of the late-stage layout changes." },
    ],
  },
  {
    id: '3d',
    tag: '3D / Motion',
    title: '3D Modeling & Animation',
    blurb: 'A short animated study exploring form, material, and motion.',
    role: 'Solo, 3D Artist',
    timeline: '1 semester',
    tools: 'Blender, After Effects',
    overview: 'For my 3D Modeling and Animation course, I modeled, textured, and animated a short scene from scratch, using it as a chance to get comfortable thinking in three dimensions instead of flat screens.',
    sections: [
      { heading: 'Modeling', body: 'I started with rough blockouts before refining geometry and adding materials, paying close attention to how light would read on each surface.' },
      { heading: 'Animation', body: 'I storyboarded a short sequence, then rigged and animated the motion in Blender before compositing final passes in After Effects.' },
      { heading: 'Reflection', body: "Working in 3D pushed me to think about depth, lighting, and pacing in ways flat UI work doesn't. Those are lessons I still carry into product design." },
    ],
    reflection: "This project had no spec and no user to design for but myself, just a shape I wanted to bring to life. That freedom made it harder, not easier, and reminded me how much a good constraint actually helps.",
  },
  {
    id: 'coding',
    tag: 'Creative Code',
    title: 'Introduction to Creative Coding',
    blurb: 'Generative sketches exploring code as a design material.',
    role: 'Solo, Creative Coder',
    timeline: '1 semester',
    tools: 'p5.js, JavaScript',
    overview: 'This course introduced me to code as a creative tool rather than just a means to build interfaces. Each project started as a simple rule or constraint that grew into a generative sketch.',
    sections: [
      { heading: 'Exploration', body: 'I experimented with loops, randomness, and simple physics to see how small rules could produce unexpected, organic-feeling results.' },
      { heading: 'Iteration', body: 'Each sketch went through dozens of small tweaks: adjusting color, timing, and density until the piece felt intentional rather than accidental.' },
      { heading: 'Takeaway', body: 'Creative coding changed how I think about interaction design: constraints and systems can produce more interesting results than designing every detail by hand.' },
    ],
    reflection: "I came into this class thinking of code purely as implementation. Watching a five-line rule produce something I didn't fully predict changed that. I now sketch interaction ideas in code, not just Figma, when I want to see how something actually behaves.",
  },
];
