// Portfolio content — ported from the Claude Design canvas artifact.
const PROJECTS = [
  {
    id: 'jpmc',
    tag: 'Enterprise Tool',
    title: 'JPMC Corporate Challenge — Report Hub',
    blurb: 'Redesigning how stakeholders track, and share event reports.',
    role: 'Product Management',
    timeline: '10 weeks',
    tools: 'Jira, Confluence',
    overview: "Reporting is critical to running JPMC's global Corporate Challenge events — it's how Admins and Local Race Organizers manage thousands of company teams and participant logistics across 16 cities. The existing reports ran on AWS QuickSight, but with CCB support for that platform ending, staying on it created a security and compliance risk. I led product management for the migration to a custom-built reporting solution.",
    sections: [
      { heading: 'The Problem', body: "QuickSight support was being sunset, and alternatives like Tableau ran into external-access constraints for our user base. We needed a path that kept reporting supported, secure, and accessible to business users — without losing what Admins and Local Race Organizers relied on day to day." },
      { heading: 'The Approach', body: "I scoped the work around getting our core business users — OBE Administrators and Local Race Organizers (LROs) — access to the reports and data they needed for day-to-day operations, so nothing broke on cutover." },
      { heading: 'Delivery & Readiness', body: "A small, focused team worked through the business requirements and delivered a custom replacement for the existing reporting suite within a few sprints. Product, Tech, and DCE completed validations to support a smooth launch, with close monitoring as usage ramped up. We also leaned on AI tooling (Copilot) for UI scaffolding, test/load testing, and synthetic data generation — an estimated ~50% improvement in delivery productivity." },
      { heading: 'The Outcome', body: "Report Hub is now live for OBE Administrators and Local Race Organizers across all 16 cities, giving them a supported, secure, custom-built home for reporting fully off QuickSight." },
    ],
    reflection: "This was my first time owning a migration end-to-end rather than a single feature. Scoping the work around what business users actually needed forced me to get comfortable saying 'not yet' to nice-to-haves so the essentials shipped on time — a tradeoff I now default to on every roadmap.",
  },
  {
    id: 'closet',
    tag: 'Mobile App',
    title: 'Closet Mind — Mindful Wardrobe App',
    blurb: 'Helping people build outfits from clothes they already own.',
    role: 'UX/UI Designer',
    timeline: '1 semester',
    tools: 'Figma, User Research',
    overview: 'For my Principles of Digital Design course, I designed Closet Mind, a mobile app that helps people plan outfits using their existing wardrobe instead of buying something new. This was the first project where I owned the full process myself — research, definition, design, and testing.',
    reflection: "This was my first project built entirely from my own research instead of a client brief, which meant I couldn't lean on anyone else's assumptions about the user. It pushed me to trust — and then test — my own instincts.",
    blocks: [
      { type: 'story', body: 'Placeholder — the "why ClosetMind" narrative: what pulled me toward this problem, and why it felt worth solving.' },
      { type: 'quote', quote: 'Placeholder pull-quote framing the core problem.', points: ['Placeholder supporting point one', 'Placeholder supporting point two', 'Placeholder supporting point three'] },
      { type: 'audience', heading: "Who It's For", cards: [
        { title: 'Placeholder audience A', body: 'Placeholder description of this audience segment.' },
        { title: 'Placeholder audience B', body: 'Placeholder description of this audience segment.' },
        { title: 'Placeholder audience C', body: 'Placeholder description of this audience segment.' },
      ]},
      { type: 'divider', kicker: 'Part One', title: 'Thinking & Process' },
      { type: 'imageNote', heading: 'Early Sketches', note: 'Placeholder note on early ideation sketches.', count: 3 },
      { type: 'imageNote', heading: 'Style References', note: 'Placeholder note on mood/inspiration references.', count: 4 },
      { type: 'columns', heading: 'Design System', items: [
        { title: 'Color', body: 'Placeholder — palette notes.' },
        { title: 'Type', body: 'Placeholder — typography notes.' },
        { title: 'Components', body: 'Placeholder — component notes.' },
      ]},
      { type: 'features', heading: 'What It Does', items: [
        { title: 'Placeholder feature 1', body: 'Placeholder feature description.' },
        { title: 'Placeholder feature 2', body: 'Placeholder feature description.' },
        { title: 'Placeholder feature 3', body: 'Placeholder feature description.' },
        { title: 'Placeholder feature 4', body: 'Placeholder feature description.' },
      ]},
      { type: 'divider', kicker: 'Part Two', title: 'Exploration & Iteration' },
      { type: 'imageNote', heading: 'Exploration Options', note: 'Placeholder note on options considered before converging.', count: 3 },
      { type: 'beforeAfter', heading: 'Iteration: Round 1', title: 'Placeholder round 1 title' },
      { type: 'beforeAfter', heading: 'Iteration: Round 2', title: 'Placeholder round 2 title' },
      { type: 'story', heading: 'Working With Claude', body: "Placeholder — an honest reflection on collaborating with AI during the process: what it helped with, what it didn't, and how it changed my workflow." },
      { type: 'divider', kicker: 'Part Three', title: 'The Final Solution' },
      { type: 'imageNote', heading: 'Key Screens', note: 'Placeholder — final screens showcase.', count: 4 },
      { type: 'imageNote', heading: 'Flow Walkthrough', note: 'Placeholder — end-to-end step-by-step walkthrough.', count: 5 },
      { type: 'reflectionBlock', quote: 'Placeholder closing quote.', takeaways: ['Placeholder takeaway one', 'Placeholder takeaway two', 'Placeholder takeaway three'] },
    ],
  },
  {
    id: 'cafeminty',
    tag: 'Brand & Web',
    title: 'Café Minty',
    blurb: 'A personal brand hub for the matcha and desserts I make at home.',
    role: 'Solo — Brand & UX/UI Designer',
    timeline: 'Weeks 12–15, 1 semester',
    tools: 'Claude Design, Photography',
    liveUrl: 'https://cafe-minty.netlify.app/',
    overview: "Café Minty is a unified brand hub for a home café idea I've had for a while but never built: a place to share matcha recipes, and eventually give people a real way to try what I make, through an order drop or pop-up. It launches matcha-first but is designed as a system that can expand into coffee, desserts, and whatever comes next, without needing a redesign.",
    reflection: "Building something I'd only ever thought about, rather than a class-assigned brief, forced me to define my own scope and know when to stop polishing and ship. Class crit pushing me to be bolder — and my own instinct to cut what wasn't real yet — were both lessons in trusting a point of view.",
    blocks: [
      { type: 'story', kicker: 'Product Story', body: "I love making matcha at home, and I've always loved hosting and feeding people — but this idea has only ever lived in my head. This project was my chance to actually build it for the first time: to figure out what it looks like, how it should feel, and whether it's something I'd genuinely want to keep going after the semester ends." },
      { type: 'story', kicker: "Who It's For", body: "Right now, friends and family who see something I post on my personal Instagram and DM me asking how to make it. But it's built for anyone who finds my content — and eventually, local customers who want to order or catch a pop-up." },
      { type: 'story', kicker: 'The Value', body: "Once Café Minty exists, that same audience gets a place to actually find and return to recipes, instead of a one-off DM reply — and, longer-term, a real way to order or catch a pop-up." },
      { type: 'story', kicker: 'My Role', body: 'Solo — brand and UX/UI design, weeks 11–14 of the semester, built in Figma with original photography.' },
      { type: 'quote', quote: "I have no diary-like place to even remember my own recipes, let alone somewhere for others to find them or know about a future order drop or pop-up.", points: [
        "Instagram can't hold recipes people return to.",
        "No way for anyone to actually order or find out about a pop-up.",
        "The idea only ever lived in my head — never had a real shape.",
      ]},
      { type: 'audience', heading: 'The Audience', cards: [
        { title: 'Friends & Family', body: "The first audience — people already DMing me for recipes off my personal Instagram." },
        { title: 'Content Followers', body: "Anyone who finds Café Minty through content I share, even without a prior connection to me." },
        { title: 'Local Customers', body: "Longer-term: people discovering it through a real pop-up or order drop." },
      ]},
      { type: 'divider', num: '01', kicker: 'Part One', title: 'Thinking & Process' },
      { type: 'imageNote', heading: 'Early Sketches', note: 'Started from paper sketches exploring layout and tone before touching Figma.', count: 3 },
      { type: 'imageNote', heading: 'Style References', note: 'Looked at warm, food-forward brands and soft, handmade packaging for tone.', count: 3 },
      { type: 'columns', heading: 'Building the System', items: [
        { title: 'Color', body: 'Warm, muted tones meant to feel like a home kitchen, not a café chain.' },
        { title: 'Type', body: 'A soft serif for warmth paired with a clean sans for labels and UI text.' },
        { title: 'Components', body: 'Recipe cards, order/pop-up states, and nav built to scale past matcha.' },
      ]},
      { type: 'features', heading: 'What It Does', items: [
        { title: 'Recipe Browsing', body: 'Browse an initial matcha recipe lineup by category.' },
        { title: 'Order Drop & Pop-Up Module', body: "Open, closed, and empty states — honest about what's actually live." },
        { title: 'Brand Story', body: 'The homepage carries the personal "why" behind Café Minty.' },
        { title: 'Real Photography', body: 'Original photography and a simple logo/wordmark, no stock or stand-ins.' },
      ]},
      { type: 'divider', num: '02', kicker: 'Part Two', title: 'Exploration & Iteration' },
      { type: 'styleDirections',
        heading: 'Three directions, then a blend',
        directions: [
          { title: 'A — Terracotta / editorial serif', sub: 'Warm, food-forward, grounded', type: 'Georgia / system sans',
            palette: ['oklch(96% 0.012 80)', 'oklch(55% 0.13 40)', 'oklch(63% 0.09 140)', 'oklch(60% 0.09 65)', 'oklch(65% 0.09 5)'],
            verdict: 'What I already had. Safe and cohesive, reads as "café" — but it played it straight and never felt like mine specifically.' },
          { title: 'B — Clay & sage / rounded serif', sub: 'Softer, friendlier, more handmade', type: 'Rounded slab serif / system sans',
            palette: ['oklch(96% 0.014 80)', 'oklch(60% 0.11 45)', 'oklch(64% 0.09 140)', 'oklch(76% 0.11 80)', 'oklch(68% 0.10 0)'],
            verdict: 'The rounded serif made it feel more handmade and personal — closer to "made by Martha" than "designed by a studio."' },
          { title: 'C — Charcoal & clay / high-contrast serif', sub: 'More minimal, closer to a design portfolio', type: 'High-contrast serif / mono-ish sans',
            palette: ['oklch(96% 0.012 80)', 'oklch(22% 0.008 60)', 'oklch(56% 0.13 40)', 'oklch(63% 0.09 140)', 'oklch(60% 0.09 65)'],
            verdict: 'The most minimal and editorial — elevated, but risked feeling less warm and approachable for a food brand.' },
          { title: "D — Blend: B's warmth, C's structure", sub: 'Clay, sage & rose palette, sharper corners, quieter serif', chosen: true, type: 'Georgia serif, restrained tracking / system sans body',
            palette: ['oklch(96% 0.014 80)', 'oklch(22% 0.008 60)', 'oklch(60% 0.11 45)', 'oklch(64% 0.09 140)', 'oklch(68% 0.08 0)'],
            verdict: "B brings the warmth and human feel, C brings the restraint and structure — so it reads as designed, not soft. Charcoal became the primary action color throughout." },
        ],
        blendLogic: "One late change mattered more than it looked: I swapped the dessert accent from gold back to dusty rose. The gold sat too close to clay and matcha — all three read as “warm/food” and blurred together. Rose is cooler, so it separates cleanly as its own category. That locked the trio: sage for matcha, clay for coffee, dusty rose for dessert, on a cream and charcoal neutral base.",
      },
      { type: 'colorDecision',
        heading: 'Designing a palette that survives the menu growing',
        intro: "Café Minty launches matcha-first, but I knew from the start it wouldn't stay matcha-only — I plan to expand into coffee and desserts. So the real design question wasn't “what colors do I like,” it was: how do I build a visual system today that doesn't box me into a redesign later? I made the tradeoffs concrete by showing how each approach would actually handle matcha, coffee, and dessert side by side.",
        options: [
          { title: 'Neutral base, rotating accent', sub: 'Same bones, accent color signals category', chosen: true,
            verdict: "The color tells you what section you're in before you read a word, and a fourth category later means adding one accent — not rethinking the brand.",
            swatches: [
              { label: 'Matcha', color: 'oklch(62% 0.09 145)' },
              { label: 'Coffee', color: 'oklch(58% 0.11 50)' },
              { label: 'Dessert', color: 'oklch(68% 0.09 5)' },
            ]},
          { title: 'One signature color', sub: 'Ingredient-agnostic, color = you',
            verdict: 'Lowest maintenance and the most single-minded brand, but weak wayfinding — every category looks identical, so the palette does no navigational work.',
            swatches: [
              { label: 'Matcha', color: 'oklch(58% 0.11 50)' },
              { label: 'Coffee', color: 'oklch(58% 0.11 50)' },
              { label: 'Dessert', color: 'oklch(58% 0.11 50)' },
            ]},
          { title: 'Photography-led, near-neutral', sub: 'Let the food carry the color',
            verdict: "The most authentic option, but fragile — it only holds up as long as photo quality and consistency do, and that's a standard I'd have to hit on every single post.",
            swatches: [
              { label: 'Matcha', color: 'oklch(80% 0.02 90)' },
              { label: 'Coffee', color: 'oklch(80% 0.02 90)' },
              { label: 'Dessert', color: 'oklch(80% 0.02 90)' },
            ]},
        ],
        criteria: "I chose the rotating-accent system because it optimizes for the two things I cared about most: instant orientation for the customer, and extensibility — adding a fourth category later means adding one new accent into an existing system.",
        tradeoff: "More ongoing color governance. Every new category's accent has to still feel cohesive with the others, so I'm treating the neutral base and typography as the fixed constraint that keeps it all reading as one brand.",
        close: "This mirrors how I approach product decisions at work — I don't just pick the option that looks best today, I think about what happens when the scope grows, because I've seen what it costs to retrofit a system that wasn't built to extend.",
      },
      { type: 'beforeAfter', heading: 'Iteration: The Headline',
        title: "The first version explained the business in four lines. The second says what it actually is in one — “A little something, made for sharing” — and moves the warmth into the subhead, where a personal reason (“I've always loved hosting”) does more work than a product description. The nav also arrived here, so the page stopped floating." },
      { type: 'beforeAfter', heading: 'Iteration: The Order Module',
        title: "The first version invented momentum — a live “This week's drop,” a scarcity line, a pop-up at a real market on a date I made up. It looked impressive and none of it was true. I replaced it with an honest empty state that keeps the section useful (“waiting on something sweet? so am I” + Notify me) instead of faking activity I couldn't deliver." },
      { type: 'workingWithAI', heading: 'Process, Honestly', helped: [
        'Speeding up variations of homepage layout and component states.',
        'Drafting copy options to react to and cut down from.',
      ], fellShort: [
        "Read as too safe and quiet at first — class crit, not AI, pushed the bolder direction.",
        'Needed my own judgment to catch the nav order mismatch and swap in real photography.',
      ]},
      { type: 'divider', num: '03', kicker: 'Part Three', title: 'The Final Solution' },
      { type: 'imageNote', heading: 'Key Screens', note: 'Homepage, recipe pages, and the order/pop-up module.', count: 4 },
      { type: 'imageNote', heading: 'End to End', note: 'Walking through finding a recipe to checking pop-up status.', count: 4 },
      { type: 'reflectionBlock', quote: "Every real change pushed the same direction: toward less, but truer.", keepGoing: 'Open real ordering and expand the recipe lineup past matcha into coffee and desserts.', differently: "Would have scoped the order/pop-up module earlier — it drove most of the late-stage layout changes." },
    ],
  },
  {
    id: '3d',
    tag: '3D / Motion',
    title: '3D Modeling & Animation Capstone',
    blurb: 'A short animated study exploring form, material, and motion.',
    role: 'Solo — 3D Artist',
    timeline: '1 semester',
    tools: 'Blender, After Effects',
    overview: 'For my 3D Modeling and Animation course, I modeled, textured, and animated a short scene from scratch — using it as a chance to get comfortable thinking in three dimensions instead of flat screens.',
    sections: [
      { heading: 'Modeling', body: 'I started with rough blockouts before refining geometry and adding materials, paying close attention to how light would read on each surface.' },
      { heading: 'Animation', body: 'I storyboarded a short sequence, then rigged and animated the motion in Blender before compositing final passes in After Effects.' },
      { heading: 'Reflection', body: "Working in 3D pushed me to think about depth, lighting, and pacing in ways flat UI work doesn't — lessons I still carry into product design." },
    ],
    reflection: "This project had no spec and no user to design for but myself — just a shape I wanted to bring to life. That freedom made it harder, not easier, and reminded me how much a good constraint actually helps.",
  },
  {
    id: 'coding',
    tag: 'Creative Code',
    title: 'Introduction to Creative Coding',
    blurb: 'Generative sketches exploring code as a design material.',
    role: 'Solo — Creative Coder',
    timeline: '1 semester',
    tools: 'p5.js, JavaScript',
    overview: 'This course introduced me to code as a creative tool rather than just a means to build interfaces. Each project started as a simple rule or constraint that grew into a generative sketch.',
    sections: [
      { heading: 'Exploration', body: 'I experimented with loops, randomness, and simple physics to see how small rules could produce unexpected, organic-feeling results.' },
      { heading: 'Iteration', body: 'Each sketch went through dozens of small tweaks — adjusting color, timing, and density until the piece felt intentional rather than accidental.' },
      { heading: 'Takeaway', body: 'Creative coding changed how I think about interaction design: constraints and systems can produce more interesting results than designing every detail by hand.' },
    ],
    reflection: "I came into this class thinking of code purely as implementation. Watching a five-line rule produce something I didn't fully predict changed that — I now sketch interaction ideas in code, not just Figma, when I want to see how something actually behaves.",
  },
];
